baseurl = "http://www.jamesbowman.me/"
languageCode = "en-us"
title = "James Bowman"
copyright = "James Bowman"
disqusShortname = "jamesebowman"

[params]
  author = "James Bowman"
  authorname = "James Bowman"
  twitter = "https://twitter.com/jamesebowman"
  github = "https://github.com/james-bowman"
  linkedin = "https://uk.linkedin.com/in/jamesedwardbowman"
  disqus = "jamesebowman"
  